### ISSUE TITLE
Convert to POST Requests

### ISSUE THREAD

**Issue by jbyman** [jbyman/covid-hackathon#41]
Because it was rushed, we implemented the APIs are purely JSON-encoded GET requests. We should enforce POST on these requests.

If possible, we should think about adding some validation or rate limiting to the requests, so we don't get DDOS'd by some malicious actor!

Bonus: I think we have very little input sanitation for our requests. That would probably be helpful to do as well!

**Comment by karishay** [comment]
Should allow posts for all relevant endpoints. (Anything that needs a body)
This is done for matching.
